### ISSUE TITLE
If N3 as rulebook language, then how to restrict the power of this language in public rule books?

### ISSUE THREAD

**Issue by phochste** [MellonScholarlyCommunication/spec-rulelanguage#4]
The N3 rule language is very expressive in combination with a reasoning engine any computation imaginable is possible.
For instance, [EYE](http://eulersharp.sourceforge.net) demonstrates the [turing completeness](https://github.com/josd/eye/tree/master/reasoning/turing) of the reasoning engine only requiring the build-in http://eulersharp.sourceforge.net/2003/03swap/log-rules namespace built-in functions. The built-in functions in this namespace itself allows for the arbitrary execution of prolog code. 

This is a bit too much power when accepting arbitrary public rulebooks. 

Are there any other options here?

**Comment by phochste** [comment]
This is typical for EYE implementation. In general the N3 built-ins are harmless https://w3c.github.io/N3/spec/#builtins

**Comment by mielvds** [comment]
I don't see this as a problem. Most rules would be quite simple and since we would be requiring N3 support, the rulebooks would always be iteroperable. However, to simplify things, we could define a subset of features + vocabularies that should be supported. Another option is to create an abstraction, but that wouldn't add much.

**Comment by phochste** [comment]
@mielvds I asked Jos De Roo to support a restricted version of EYE (only containing a minimum set of vocabs), he was very positive about it.
